version: '3.9'

services: 
  backend:
    build: ./src/backend
    ports: 
      - 8000:5000

  mongo:
    image: mongo
    ports:
      - 27017:27017

  frontend:
    build: ./src/frontend

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 81:81
    depends_on:
      - frontend
    volumes:
      - ./src/proxy/conf.d/:/etc/nginx/conf.d/